### ISSUE TITLE
Get WS2801 working

### ISSUE THREAD

**Issue by strobma** [scottlawsonbc/audio-reactive-led-strip#81] opened 2017-10-17 20:18 UTC
Is there any possibility to get a WS2801 strip correctly working?

**Comment by d-rez** [comment] 2017-10-25 18:11
Duplicate of #47

**Comment by joeybab3** [comment] 2019-07-23 17:02
Solved in recent edit where we removed the custom ws2812 library, thanks @d-rez for flagging this.

**Closed by joeybab3** 2019-07-23 17:02 UTC
